//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nfcmai
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KeptorDBEntities : DbContext
    {
        public KeptorDBEntities()
            : base("name=KeptorDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TreasureHuntGames> TreasureHuntGames { get; set; }
        public virtual DbSet<TreasureHuntParticipants> TreasureHuntParticipants { get; set; }
        public virtual DbSet<TreasureHuntTips> TreasureHuntTips { get; set; }
    }
}
