//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nfcmai
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreasureHuntParticipants
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TreasureHuntParticipants()
        {
            this.TreasureHuntTips = new HashSet<TreasureHuntTips>();
            this.TreasureHuntGames1 = new HashSet<TreasureHuntGames>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> TreasureHuntId { get; set; }
    
        public virtual TreasureHuntGames TreasureHuntGames { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TreasureHuntTips> TreasureHuntTips { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TreasureHuntGames> TreasureHuntGames1 { get; set; }
    }
}
