//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nfcmai
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreasureHuntTips
    {
        public int Id { get; set; }
        public Nullable<int> TreasureHuntGamesId { get; set; }
        public string Picture { get; set; }
        public string Titlos { get; set; }
        public string Keimeno { get; set; }
        public Nullable<bool> IsFinal { get; set; }
        public Nullable<int> TakenBy { get; set; }
        public string HFCode { get; set; }
        public Nullable<bool> IsFirst { get; set; }
    
        public virtual TreasureHuntGames TreasureHuntGames { get; set; }
        public virtual TreasureHuntParticipants TreasureHuntParticipants { get; set; }
    }
}
